---
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          url: https://github.com/rseroter/pluralsight-spring-cloudconfig-wa-tolls
#          username: uname
#          password: pass